from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "output" / "pdf" / "TUNISIA_SOLAR_FORECASTING_TECHNICAL_REPORT_REVISED.pdf"
OUT.parent.mkdir(parents=True, exist_ok=True)

NAVY = colors.HexColor("#0B1324")
BLUE = colors.HexColor("#1D4ED8")
SLATE = colors.HexColor("#334155")
LIGHT = colors.HexColor("#F1F5F9")
MUTED = colors.HexColor("#64748B")
styles = getSampleStyleSheet()
styles.add(ParagraphStyle(name="C", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=24, leading=29, textColor=NAVY, alignment=1, spaceAfter=8))
styles.add(ParagraphStyle(name="H1x", parent=styles["Heading1"], fontName="Helvetica-Bold", fontSize=17, leading=21, textColor=NAVY, spaceAfter=8))
styles.add(ParagraphStyle(name="H2x", parent=styles["Heading2"], fontName="Helvetica-Bold", fontSize=11, leading=14, textColor=BLUE, spaceBefore=7, spaceAfter=4))
styles.add(ParagraphStyle(name="B", parent=styles["BodyText"], fontName="Helvetica", fontSize=8.3, leading=11.3, textColor=SLATE, spaceAfter=5))
styles.add(ParagraphStyle(name="S", parent=styles["BodyText"], fontName="Helvetica", fontSize=7.2, leading=9.4, textColor=SLATE, spaceAfter=3))
styles.add(ParagraphStyle(name="Call", parent=styles["BodyText"], fontName="Helvetica-Bold", fontSize=8.8, leading=12, textColor=NAVY, backColor=LIGHT, borderColor=colors.HexColor("#CBD5E1"), borderWidth=.5, borderPadding=7, spaceAfter=7))

def p(x, s="B"): return Paragraph(x, styles[s])
def bullets(items): return [p("? " + x) for x in items]
def tbl(rows, widths, header=True):
    data = [[p(str(x), "S") for x in row] for row in rows]
    t = Table(data, colWidths=widths, repeatRows=1 if header else 0)
    cmd=[("GRID",(0,0),(-1,-1),.35,colors.HexColor("#CBD5E1")),("VALIGN",(0,0),(-1,-1),"TOP"),("ROWBACKGROUNDS",(0,1 if header else 0),(-1,-1),[colors.white,colors.HexColor("#F8FAFC")]),("LEFTPADDING",(0,0),(-1,-1),5),("RIGHTPADDING",(0,0),(-1,-1),5),("TOPPADDING",(0,0),(-1,-1),4),("BOTTOMPADDING",(0,0),(-1,-1),4)]
    if header: cmd += [("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),colors.white)]
    t.setStyle(TableStyle(cmd)); return t
def boxes(rows, widths):
    return tbl(rows, widths, header=False)
def page_title(h, sub):
    return [p(h,"H1x"),p(sub,"S")]
def hf(canvas, doc):
    w,h=A4; canvas.saveState(); canvas.setFillColor(NAVY); canvas.rect(0,h-7*mm,w,7*mm,fill=1,stroke=0); canvas.setFont("Helvetica",7); canvas.setFillColor(MUTED); canvas.drawString(18*mm,10*mm,"Tunisia Solar Forecasting & STEG Dispatch Platform"); canvas.drawRightString(w-18*mm,10*mm,f"Page {doc.page} / 9"); canvas.restoreState()

story=[]
# 1
story += [Spacer(1,18*mm),p("TUNISIA SOLAR POWER FORECASTING","C"),p("& GRID DISPATCH PLATFORM","C"),p("Revised Technical Engineering Report","S"),Spacer(1,7*mm)]
story += [boxes([["Citizen interface","STEG admin interface"],["Next.js web application","Next.js web application"],["FastAPI + authentication + roles","FastAPI + authentication + roles"],["PostgreSQL","Forecast, battery, dispatch and risk services"]],[78*mm,78*mm]),Spacer(1,8*mm),p("Executive summary","H2x"),p("The platform forecasts photovoltaic production for Tunisia at national, district and governorate levels. It combines historical solar and weather information, a benchmarked machine-learning pipeline, calibrated prediction intervals, battery workflows and a provisional operational-risk layer. The current product is a Next.js and FastAPI web platform with separate citizen and STEG experiences.","B"),p("Scope: 24 governorates, 7 regional districts, intraday and multi-day horizons, citizen battery requests, STEG dispatch planning, role-based access and multilingual presentation.","Call"),p("Important limitation","H2x"),p("Real plant or SCADA measurements are not yet available. The risk layer is therefore provisional and supports, rather than replaces, operational review.","B"),p("This revision reduces the general frontend description and adds the ML pipeline, battery module and risk module as first-class sections.","B"),PageBreak()]
# 2
story += page_title("1. System architecture","A decoupled architecture separates user experience, security, forecasting and decision support.")
story += [boxes([["Browser clients","API boundary","Core services","Persistence"],["Citizen UI / STEG UI","FastAPI / CORS / JWT / roles","Forecast / Battery / Risk / Dispatch","PostgreSQL / archives / tokens"]],[42*mm,42*mm,48*mm,42*mm]),p("Request flow","H2x"),p("A browser request reaches FastAPI. The backend authenticates the user, checks the role, validates the request and calls only the required service. The frontend never receives secrets and does not call the model or weather providers directly. Forecast results, battery requests, email-token state and audit information are handled through the database layer.","B"),p("Operational scales","H2x"),tbl([["Scale","Purpose"],["National","Aggregate production for national balance and reserve planning."],["District","Compare the seven regional control areas."],["Governorate","Provide location-specific citizen and operator forecasts."]],[35*mm,130*mm]),p("Security boundary","H2x"),bullets(["JWT authentication and role separation between CITIZEN and ADMIN users.","Email verification and reset tokens are short-lived, signed and single-use.","Secrets are environment variables and never sent to the browser.","Agent or AI requests pass through authenticated backend routes."]),PageBreak()]
# 3
story += page_title("2. Data and feature preparation","The pipeline turns weather and solar information into a stable model input matrix.")
story += [p("Data foundation","H2x"),p("The benchmark corpus covers hourly historical information from 2005 to 2023 across 24 governorates. It combines solar-generation and irradiance information with temperature, humidity, pressure, precipitation, wind and layered cloud cover. Live forecast weather is ingested separately for inference.","B"),p("Preprocessing decisions","H2x"),tbl([["Stage","Treatment"],["Quality and typing","Missing-value checks, physical bounds, location handling and memory-conscious numeric types."],["Collinearity","Remove total cloud cover when it duplicates low, mid and high cloud components."],["Circular variables","Represent hour, month, day and wind direction with sine/cosine pairs."],["Scaling","Fit StandardScaler on training data only and reuse it for validation, test and inference."],["Temporal split","Keep train, validation and test periods chronological."]],[37*mm,128*mm]),p("Target and normalization","H2x"),p("The model predicts normalized photovoltaic power per installed capacity. The API scales the result to the selected capacity and presents it in kW or MW, keeping the learned model independent from incomplete or changing plant registries.","B"),p("Data limitation","H2x"),p("Simulated or historical targets support a prototype, but production validation must compare predictions with meter or SCADA data when available.","Call"),PageBreak()]
# 4
story += page_title("3. Machine-learning pipeline architecture","The ML system is evaluated as a chronological pipeline, not as a single model.")
story += [boxes([["Historical + weather data"],["Quality and physical checks"],["Feature engineering: cyclical time + weather + location"],["Chronological split: train / validation / test"],["Scaling + feature lock"],["Benchmark: 9 regression candidates"],["Selected Keras MLP"],["Uncertainty calibration: lower / expected / upper"],["Inference API: forecast + interval + metadata"]],[120*mm]),p("Selected model","H2x"),p("The selected Keras neural network is a multilayer perceptron with a 128-64-32 hidden-layer structure, ReLU activations and one linear output for normalized power. It uses Adam, mean-squared-error training and early stopping. The saved artifact preserves topology, weights and feature-order metadata.","B"),p("Benchmark summary","H2x"),tbl([["Model","RMSE","MAE","R2","MAPE","Status"],["keras_nn","0.759","0.334","0.99999","2.05%","Selected"],["mlp","0.921","0.412","0.99998","2.61%","Fallback"],["xgboost","1.024","0.453","0.99997","1.87%","Benchmarked"],["lightgbm","1.031","0.461","0.99997","1.92%","Benchmarked"],["linear regression","12.847","7.231","0.99712","31.70%","Baseline"]],[35*mm,20*mm,20*mm,22*mm,22*mm,45*mm]),p("Selection principle","H2x"),p("Training time is secondary. Keras was selected mainly for lower test error; training time is monitored for retraining. Runtime is assessed separately through API latency and throughput benchmarks.","B"),PageBreak()]
# 5
story += page_title("4. Forecasting and uncertainty","The platform exposes a prediction interval so users can plan around uncertainty.")
story += [p("Live inference sequence","H2x"),bullets(["Fetch the selected horizon and location weather data.","Compute solar-position and plane-of-array features.","Apply locked feature order and training scaler.","Run the model and enforce physical non-negative output.","Return expected production, lower bound, upper bound, certitude and metadata."]),p("Interval calibration","H2x"),p("A calibration layer estimates lower and upper bounds from validation residuals. The margin changes by irradiance regime and weather variability. At night, photovoltaic output and its bounds are clamped to zero. During daylight, certitude decreases as the interval becomes wider relative to expected production.","B"),tbl([["Output","Meaning"],["Expected","Most likely production for the selected time and location."],["Lower","Conservative value used to understand possible shortfall."],["Upper","Higher plausible value; not a guarantee."],["Certitude","Readable indication of interval width and forecast confidence."]],[32*mm,133*mm]),p("Performance evidence","H2x"),p("API benchmarks measure success rate, average latency, p95 latency and throughput for forecast, spatial summary, dispatch preview and telemetry. This separates model accuracy from application performance.","B"),p("Interpretation warning","H2x"),p("Very high R2 values require checks for chronological separation, duplicates and leakage. They are not proof of field accuracy until plant measurements confirm them.","Call"),PageBreak()]
# 6
story += page_title("5. Battery module","The battery workflow connects citizen needs with an auditable STEG review process.")
story += [boxes([["Citizen profile"],["PV capacity + location + consumption"],["Battery catalogue"],["Compatibility and sizing checks"],["Battery request"],["STEG review and decision"],["Installation lifecycle"],["ACTIVE battery guidance"]],[120*mm]),p("Citizen capabilities","H2x"),bullets(["Choose the governorate where the installation is located.","Browse battery products and technical specifications.","Enter appliances, power and expected usage.","Submit a request and follow installation milestones.","Receive reserve, charging and discharging guidance only after ACTIVE status."]),p("STEG capabilities","H2x"),bullets(["Review citizen, battery and appliance information.","Run an engineering-oriented audit for compatibility, autonomy, self-consumption and sizing.","Approve, reject or request information.","Manage approved, scheduled, installing, commissioning and active stages.","Use forecast and risk context when reviewing operational implications."]),p("Status rule","H2x"),p("SUBMITTED, UNDER_REVIEW, INFO_REQUESTED, APPROVED, INSTALLATION_SCHEDULED, INSTALLING, COMMISSIONING and REJECTED are not active. Only ACTIVE enables citizen battery recommendations.","Call"),p("Boundary","H2x"),p("The module supports sizing and workflow decisions. It does not claim physical battery control unless a verified future control integration is added.","B"),PageBreak()]
# 7
story += page_title("6. Provisional risk module","The risk layer translates interval uncertainty and weather conditions into guidance.")
story += [boxes([["Expected + lower + upper + certitude"],["Weather: clouds, rain, wind, variability"],["Risk classification"],["Low / medium / high"],["Audience-specific guidance"],["Citizen battery advice / STEG reserve + dispatch"]],[120*mm]),p("Weather enrichment","H2x"),p("OpenWeather is called only by the backend using OPEN_WEATHER_API_KEY. The key is never sent to the browser. The service extracts cloud cover, rain, wind and short-horizon variability. If the provider or key is unavailable, the forecast continues and weather enrichment is marked unavailable.","B"),p("Risk levels","H2x"),tbl([["Level","Interpretation","Action"],["Low","Narrow interval and stable context.","Follow expected forecast."],["Medium","Interval or weather adds uncertainty.","Plan conservatively and preserve reserve."],["High","Wide interval or highly variable context.","Plan near lower bound and require human review."]],[25*mm,65*mm,75*mm]),p("Citizen behavior","H2x"),p("Without an ACTIVE battery, a citizen sees production and its interval only. With an ACTIVE battery, the citizen opens a risk modal showing level, weather factors, reserve advice and charging or discharging guidance.","B"),p("STEG behavior","H2x"),p("The STEG workspace shows expected, lower and upper values, certitude, conservative planning value, possible shortfall, grid reserve, dispatch recommendation and a human-review flag. It is decision support, not automatic grid control.","B"),p("Every result is labelled provisional until SCADA or plant measurements can validate the thresholds.","Call"),PageBreak()]
# 8
story += page_title("7. Interfaces, security and operations","The frontend is concise; the technical value is the separation between citizen and STEG workflows.")
story += [p("Citizen interface","H2x"),p("The citizen UI is multilingual and location-aware. It focuses on expected production, the interval, battery requests and actionable guidance only when a battery is active. Risk details open in a modal to keep the home screen simple.","B"),p("STEG admin interface","H2x"),p("The STEG UI provides forecast controls, national and regional views, the spatial map, dispatch preview and export, the dedicated risk-operations screen, weather status and battery-request review. It uses operational language and exposes conservative values and reserve guidance.","B"),p("Authentication and token lifecycle","H2x"),tbl([["Control","Implementation"],["Login","JWT-authenticated sessions with role checks."],["Email verification","Signed HS256 token with purpose, expiry and unique identifier."],["Reset or resend","Short-lived token; old tokens revoked; each token single-use."],["Secrets","JWT and email secrets are required environment variables."],["Browser boundary","API key and internal credentials remain server-side."],["Transport","HTTPS required for production; HTTP is local development only."]],[38*mm,127*mm]),p("Reliability controls","H2x"),bullets(["Weather failure does not stop forecast responses.","Forecast data is cached and spatial aggregation uses grouped operations.","Benchmarks track p95 latency and throughput.","Invalid or missing forecast values are rejected by the risk endpoint."]),PageBreak()]
# 9
story += page_title("8. Limitations, validation plan and conclusion","The prototype is structured for extension, but production claims require field evidence.")
story += [p("Known limitations","H2x"),bullets(["Real plant or SCADA measurements are not connected, so plant-level accuracy and risk calibration remain unverified.","Capacity assumptions must be reconciled with STEG registries and meter data.","The risk layer recommends actions but does not automatically control batteries or grid assets.","High R2 values require independent leakage checks and out-of-time validation.","OpenWeather availability and quota must be monitored."]),p("Next validation gates","H2x"),tbl([["Gate","Evidence required"],["Forecast validity","Out-of-time evaluation against metered production by location and horizon."],["Interval quality","Coverage and sharpness of bounds, not only point accuracy."],["Risk usefulness","Compare risk levels with observed weather and production shortfalls."],["Battery value","Validate guidance against battery telemetry and user load profiles."],["Operations","STEG review of exports, reserve guidance and failure handling."],["Security","HTTPS, secret rotation, access-control tests and penetration review."]],[39*mm,126*mm]),p("Engineering conclusion","H2x"),p("The revised platform provides a coherent path from weather-informed forecasting to uncertainty visibility and audience-specific decision support. Its strongest current value is the separation of concerns: an understandable citizen interface and an operational STEG workspace. The next major step is connecting trusted plant measurements and validating the interval and risk layer against reality.","Call"),Spacer(1,5*mm),p("End of revised technical report","S")]
story = [item for group in story for item in (group if isinstance(group, list) else [group])]
doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=17*mm,bottomMargin=17*mm,title="Tunisia Solar Forecasting Technical Report - Revised")
doc.build(story,onFirstPage=hf,onLaterPages=hf)
print(OUT)
